#!/bin/bash
if [ -e simv ]
then
	\rm -rf simv
fi

if [ -e simv.daidir ]
then
	\rm -rf simv.daidir
fi
if [ -e csrc* ]
then
	\rm -rf csrc
fi

#verdi env setting
export PLATFORM=LINUX64
export NOVAS_INST_DIR=/home/synopsys/verdi/verdi/Verdi_O-2018.09-SP2
export LD_LIBRARY_PATH=$NOVAS_INST_DIR/share/PLI/lib/$PLATFORM:$LD_LIBRARY_PATH


#	+vcsd +memcbk \
#	-sverilog \
#	+define+USE_RAM_MODEL \


vcs 	-l vcs.log \
        -full64 \
	-notice	\
	-line -debug_all \
	-P $NOVAS_INST_DIR/share/PLI/VCS/$PLATFORM/novas.tab $NOVAS_INST_DIR/share/PLI/VCS/$PLATFORM/pli.a \
	-f vcs.args
./simv 		
